# Generated by Django 2.0.4 on 2018-04-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Answer Options',
                'verbose_name': 'Answer Option',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
                'verbose_name': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('FILL_IN_THE_BLANK', 'FILL_IN_THE_BLANK'), ('SELECT_BEST_MATCH', 'SELECT_BEST_MATCH')], max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('correct', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='Vocabulary.Answer_Options')),
                ('possible_answers', models.ManyToManyField(to='Vocabulary.Answer_Options')),
                ('quiz', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vocabulary.Quiz')),
                ('selected', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='Vocabulary.Answer_Options')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'verbose_name': 'Quiz Question',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_vocab', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=300)),
                ('image_url', models.ImageField(upload_to='word_pics/')),
            ],
            options={
                'verbose_name_plural': 'Words',
                'verbose_name': 'Word',
            },
        ),
    ]
