# Generated by Django 2.0.4 on 2018-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('COMMON', 'COMMON'), ('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('MEDIUM 2', 'MEDIUM 2'), ('MEDIUM 3', 'MEDIUM 3'), ('MEDIUM 4', 'MEDIUM 4'), ('HARD', 'HARD'), ('HARD 2', 'HARD 2'), ('HARD 3', 'HARD 3'), ('HARD 4', 'HARD 4')], default='HARD', max_length=30),
        ),
    ]
