# Generated by Django 2.0.4 on 2018-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0002_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.CharField(default='____________', max_length=300),
        ),
    ]
