# Generated by Django 2.0.4 on 2018-04-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0003_auto_20180419_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio',
        ),
    ]
