# Generated by Django 2.0.4 on 2018-04-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0004_remove_word_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
